>>>root = Node(1) 
>>>root.left = Node(2) 
>>>root.right = Node(3) 
>>>root.left.left = Node(4) 
>>>root.left.right = Node(5) 
>>>inorderTraversal(root)
[4, 2, 5, 1, 3]
>>> root = Node(1)
>>> root.left = Node(2)
>>> root.right = Node(3)
>>> root.left.left = Node(4)
>>> root.left.right = Node(5)
>>> root.right.left = Node(6)
>>> root.right.right = Node(7)
>>> inorderTraversal(root)
[4, 2, 5, 1, 6, 3, 7]
>>> root = Node(5)
>>> root.left = Node(10)
>>> root.right = Node(100)
>>> root.left.left = Node(150)
>>> root.left.right = Node(250)
>>> root.right.left = Node(550)
>>> inorderTraversal(root)
[150, 10, 250, 5, 550, 100]